# Generated by Django 3.1 on 2021-08-09 12:09

from django.db import migrations, models
import shop_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=shop_settings.models.upload_image_path, verbose_name='تصویر لوگو'),
        ),
    ]
